### PR TITLE
Port net-ipfs-api to .net core

### PR DESCRIPTION
**Pull request by lvermeulen**
Unit tests were changed to XUnit.

### CODE REVIEW

**Comment by jeremy-ellis-tech** [comment]
Much appreciated changes. Especially around the C# 6.0 features.

However, some changes move *away* from well established [code conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/).

For example:
* Implicitly typed local variables where it is not clear what the type is from either side of an assignment.
ie.  `HttpContent content = await ExecuteGetAsync(...);` vs `var content = await ExecuteGetAsync(...);`
* static/const member in ALL_CAPS_SNAKE_CASE instead of PascalCase
* Using primitive alias instead of class name for accessing static members. ie. `string.Equals(..)` vs `String.Equals(..)`.

**Comment by lvermeulen** [comment]
Ah. I follow CoreFX guidelines myself - https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md - but I recognize I may have transgressed even those. I will fix and resubmit.

**Comment by timothyparez** [comment]
If we're going to have .NET core support, shouldn't it be in a separate branch?
If we want to keep everything in one branch we should target .NET Standard instead.

**Comment by lvermeulen** [comment]
@timothyparez That's the general idea.

**Pull request closed without merging**
